erDiagram
    BOOK ||--o{ LOAN : is
    BOOK {
        string ISBN PK
        string title
        string author
        int pages
    }
    LOAN {
        int loanID PK
        datetime loanDate
        datetime returnDate		
    }
    PATRON ||--o{ LOAN : borrows
    PATRON {
        string patronID PK
        string name
        string address
        string email
    }
    LIBRARIAN ||--o{ LOAN : manages
    LIBRARIAN {
        string librarianID PK
        string name
        string department
    }
